[package]
name = "network-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
burn = "0.7.0"
burn-autodiff = "0.7.0"
burn-tch = "0.7.0"
serde = { version = "1" }
